### ISSUE TITLE
The jQuery dependencies are not present in /external

### ISSUE THREAD

**Issue by mosleymos** [jagenjo/litegui.js#11]
During my tryout of the library, I've noticed that the Jquery link in the README.md are not present on the /external folder.

```html
    <script type="text/javascript" src="litegui.js/external/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="litegui.js/external/jquery-ui-1.10.4.min.js"></script>
```

Instead I've went to the jQuery CDN and jQuery Ui to download

Could you append these dependencies on the external folder ?

**Comment by jagenjo** [comment]
jQuery is no longer a dependency as far as I remember, I removed long time ago.

It should work, Im gonna correct the readme then
