### ISSUE TITLE
how put Main area in tab

### ISSUE THREAD

**Issue by NicoBrug** [jagenjo/litegui.js#12]
Hello,

First of all, congratulations for the realization of this GUI. It is very well done. 
I would have liked to be able to put tabs to be able to access a different panel configuration. The canvas should be the same when you open the different tabs, but the panel configuration and the widgets should be different. I haven't found a solution to this question and I would like to know if it's possible to do it. I will send you a picture of what I want to do. 
Thank you

![Dessin sans titre](https://user-images.githubusercontent.com/25402899/96335489-420a7180-1079-11eb-8efc-c5f8e4d53d3f.png)

**Comment by jagenjo** [comment]
there are two ways:

detect when the tab changes and move the canvas from one container to another (thats how I do it in WebGLStudio)

or create a tabs without content and change whatever you want when the user clicks.
