### ISSUE TITLE
Detached dialog mouse events on number up/down arrows

### ISSUE THREAD

**Issue by cppctamber** [jagenjo/litegui.js#5]
When detaching a dialog the mouse events no longer work as expected on number inputs (including vector inputs).

I detached a dialog and while numbers can be manually entered  clicking the up and down arrows on them doesn't do anything, and the input amount remains the same.

However, If I left click my mouse on one of the up/down arrows, and then click the main browser window and move the mouse (no clicking required), these numbers change.

![image](https://cloud.githubusercontent.com/assets/7591350/20654787/4e8a6f70-b581-11e6-90ce-f8b57cb3ed96.png)

**Comment by jagenjo** [comment]
Yes, detaching windows could be problematic because they bind events to the main window, so events in the secondary window wont be detected. I will fix it by checking which window is the widget on before binding the events.

**Comment by jagenjo** [comment]
Ok,  I fixed the bug for updown arrows (dragger), sliders and color pickers. If you see any other problem related to detaching the window let me know, thats a very experimental feature not fully tested.

You need to download jscolor.js again because I had to change some parts.

**Comment by cppctamber** [comment]
Awesome thanks!
